server/api/index.js
server/api/products.js
server/api/users.js

add API routes for products: api/products/ ; api/products/tag/:id ; api/products/style/:type ; api/products/style/:color

add API routes for products

---

package-lock.json
package.json
server/db/models/index.js
server/db/models/item.js
server/db/models/item.spec.js

Added definition for Item table. Added unit tests for Item schema.

define item schema and test it

---

.prettierrc.yml
script/seed.js
script/seed.spec.js
server/api/users.js
server/api/users.spec.js
server/db/db.js
server/db/index.js
server/db/models/user.js
server/db/models/user.spec.js

Added user model modifications. Added unit tests for user model in additions to those previously running.

add user model and unit tests

---

client/components/AllProducts.js
client/components/SingleProduct.js
client/reducers/products.js

add products components and a thunk

---

norms.md
seed/items.json
server/db/models/item.js

Added additonal seed data & updated the models to have more colors. Not a high priority update

More seed data

---

script/seed.js
seed/users.json
server/db/models/user.js

to seed users in addition to items
Seeding database was successful.

add seed users, modify phone number definition, modify seed.js

---

client/app.js
client/components/AllProducts.js
client/components/index.js

allproducts bug fixed

---

server/db/models/index.js
server/db/models/order.js
server/db/models/order.spec.js

Order model created + tests written (and passing)

Created order model

---

package-lock.json
package.json

package may be used in front-end testing

add dev dependency on axios-mock-adapter #45

---

client/app.js
client/components/AllProducts.js
client/components/Checkout.js
client/reducers/products.js

checkout component prototype

---

server/api/index.js
server/api/orders.js
server/api/orders.spec.js
server/db/models/order.js

Routes written for get and post and tests working

Wrote order routes

---

client/components/AllProducts.js
client/components/SingleItemDetail.js
client/components/SingleProduct.js
client/routes.js

Single item detailed

---

package-lock.json
package.json
seed/items.json

changed image paths so images are found in public folder and will display *after* the db is reseeded with `npm run seed`.

update seed to show images when db is reseeded

---

client/components/SingleItemDetail.js
client/components/index.js
client/reducers/item.js
client/store/index.js
server/index.js

image still not rendering; some extraneous code still in files

single item detail page working except for image

---

client/components/Cart.js
client/components/Checkout.js
client/reducers/cart.js
client/routes.js

Checkout component - please, refer to the commits

---

client/components/SingleItemDetail.js
client/routes.js

add to cart single detail item working

---

client/app.js
client/components/Checkout.js
client/components/ThankYou.js
client/routes.js

Thank-you component

---

public/index.html

changed name displayed on tab

---

.travis.yml
package-lock.json
package.json

Modified .travis.yml to allow Travis CI to automatically deployt to Heroku after each push to the master branch. This will all users to always access a deployed site (issue #88).

Travis heroku fix #88

---

client/components/SingleProduct.spec.js
package-lock.json
package.json

Added dev dependency on sinon package.
Added some tests to SingleProduct component.
All unit tests passing.

chore: add some tests for SingleProduct component

---

client/components/navbar.js

Updated navbar so that links to products and cart are visible to logged-in clients.
All unit tests passing.

updated navbar.js to display links when logged in

---

client/components/SingleProduct.js
client/components/SingleProduct.spec.js

modified the test to reflect that SingleProduct now has two (2) link tags
all unit tests passing

chore: modify SingleProduct test

---

server/auth/index.js

removed passport to restore login to former working state

fixed login issue

---

server/api/orders.spec.js

commented out tests temporarily

---

server/index.js

Removed express-static path individualized for watches
All unit tests passing

remove extraneous static route

---

client/reducers/cart.js
server/api/orders.js
server/db/models/order.js

updated orders model with amount and isCart

---

client/components/navbar.js
public/style.css

remove duplicated logic in navbar component
update style to retain inline-block display
all unit tests passing
fixes #136

closes #136; dedupe navbar logic; update style

---

client/reducers/cart.js
server/api/orders.js
server/db/models/order.js

Authentication

---

client/utils/utilities.js
server/api/orders.js

changed utility function displayPrice to display numbers in US currency format
this fixes the problem of displaying variable numbers of decimal places

Fix number formats
